config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  mount Ckeditor::Engine => "/ckeditor"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Sidekiq::Web => "/sidekiq"
  
  root "administrator/dashboard#index"

  namespace :administrator do
    root "dashboard#index"

    devise_for :administrators, path: "", path_names: { sign_in: "login", sign_out: "logout" },
      skip: [:registrations, :passwords]

    # resources :posts do
    #   member do
    #     delete :delete_image_attachment
    #     get :copy
    #   end
    # end
    # resources :tags
    # resources :categories do
    #   member do
    #     delete :delete_image_attachment
    #   end
    # end

    # resources :reports, only: :index
  end
end

app/models/administrator.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: administrators
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_administrators_on_email                 (email) UNIQUE
#  index_administrators_on_reset_password_token  (reset_password_token) UNIQUE
#
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :bigint           not null, primary key
#  data_content_type :string(255)
#  data_file_name    :string(255)      not null
#  data_file_size    :integer
#  data_fingerprint  :string(255)
#  type              :string(30)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_ckeditor_assets_on_type  (type)
#
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::ActiveStorage

  attr_accessor :data

  has_one_attached :storage_data
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :bigint           not null, primary key
#  data_content_type :string(255)
#  data_file_name    :string(255)      not null
#  data_file_size    :integer
#  data_fingerprint  :string(255)
#  type              :string(30)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_ckeditor_assets_on_type  (type)
#
class Ckeditor::AttachmentFile < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :bigint           not null, primary key
#  data_content_type :string(255)
#  data_file_name    :string(255)      not null
#  data_file_size    :integer
#  data_fingerprint  :string(255)
#  type              :string(30)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_ckeditor_assets_on_type  (type)
#
class Ckeditor::Picture < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_content
    rails_representation_url(storage_data.variant(resize: "800>").processed, only_path: true)
  end

  def url_thumb
    rails_representation_url(storage_data.variant(resize: "118x100").processed, only_path: true)
  end
end

app/controllers/administrator/base_controller.rb
# frozen_string_literal: true

class Administrator::BaseController < ApplicationController
  before_action :authenticate_administrator_administrator!
end

app/controllers/administrator/dashboard_controller.rb
# frozen_string_literal: true

class Administrator::DashboardController < Administrator::BaseController
  def index
  end
end

app/controllers/administrator/sessions_controller.rb
# frozen_string_literal: true

class Administrator::SessionsController < Devise::SessionsController
  layout "administrator/unauthenticate_layout"

  def destroy
    flash[:success] = I18n.t("devise.sessions.signed_out") if sign_out current_administrator_administrator
    redirect_to new_administrator_administrator_session_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  FLASH_TYPE = {
    success: "success", error: "error", failed: "failed",
    alert: "error", notice: "success", danger: "danger"
  }.freeze

  def flash_class flash_type
    FLASH_TYPE[flash_type] || flash_type.to_s
  end

  def active_sidebar path, controller
    "active" if current_page?(path) || controller_name == controller
  end

  def format_date date
    date.strftime(Settings.time.formats)
  end

  def name_tag ids
    Tag.where(id: ids).pluck(:name, :color)
  end
end

app/views/administrator/dashboard/index.html.erb
<div class="dashboard">
  <div class="dashboard__calendar">
    <div class="filter">
      <img src="<%= asset_path("icon/filter.svg") %>" alt="icon-filter">
      Filter
    </div>
  </div>
  <div class="dashboard__content">
    <div class="statistical">
      <div class="statistical__item">
        <div class="item-head">
          <div class="title">Total Category</div>
          <div class="icon">
             <img class="size-24" src="<%= asset_path("icon/total_category.svg") %>" alt="icon-total-category">
          </div>
        </div>
        <div class="item-quantity">
          <div class="quantily"><%#= Category.count %></div>
          <div class="current">+<%#= Category.from_current_month %> per month</div>
        </div>
      </div>
      <div class="statistical__item">
        <div class="item-head">
          <div class="title">Total Post</div>
          <div class="icon">
            <img class="size-24" src="<%= asset_path("icon/total_product.svg") %>" alt="icon-total-product">
          </div>
        </div>
        <div class="item-quantity">
          <div class="quantily"><%#= Post.count %></div>
          <div class="current">+<%#= Post.from_current_month %> per month</div>
        </div>
      </div>
      <div class="statistical__item">
        <div class="item-head">
          <div class="title">Total Report</div>
          <div class="icon">
            <img class="size-24" src="<%= asset_path("icon/detail.svg") %>" alt="icon-reports">
          </div>
        </div>
        <div class="item-quantity">
          <div class="quantily"><%#= Report.count %></div>
          <div class="current">+<%#= Report.from_current_month %> per month</div>
        </div>
      </div>
      <div class="statistical__item">
        <div class="item-head">
          <div class="title">Total Tag</div>
          <div class="icon">
            <img class="size-24" src="<%= asset_path("icon/tag.svg") %>" alt="icon-tag">
          </div>
        </div>
        <div class="item-quantity">
          <div class="quantily"><%#= Tag.count %></div>
          <div class="current">+<%#= Tag.from_current_month %> per month</div>
        </div>
      </div>
      <div class="statistical__item">
        <div class="item-head">
          <div class="title">Total Traffic</div>
          <div class="icon">
            <img class="size-24" src="<%= asset_path("icon/activity.svg") %>" alt="icon-activity">
          </div>
        </div>
        <div class="item-quantity">
          <div class="quantily">6789</div>
          <div class="current">+100 per month</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/administrator/_header.html.erb
<div class="header">
  <div class="header__title">
    <% if @header_post %>
      <img src="<%= asset_path("icon/product.svg") %>" alt="icon-product">
      <span>Post List</span>
    <% elsif @header_category %>
      <img src="<%= asset_path("icon/category.svg") %>" alt="icon-category">
      <span>Category List</span>
    <% elsif @header_tag %>
      <img src="<%= asset_path("icon/tag.svg") %>" alt="icon-tag">
      <span>Tag List</span>
    <% elsif @header_report %>
      <img src="<%= asset_path("icon/detail.svg") %>" alt="icon-report">
      <span>Report List</span>
    <% end %>
  </div>
  <div class="header__user">
    <span><%= current_administrator_administrator.email %></span>
    <%= button_to destroy_administrator_administrator_session_path, method: :delete, data: { turbo: false }, class: "btn-out-style" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#2F4858" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
        <circle cx="12" cy="7" r="4"></circle>
      </svg>
    <% end %>
  </div>
</div>

app/views/layouts/administrator/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar__logo">
    <a href="<%= administrator_root_path %>">
      <img src="<%= asset_path("logo-haotruong.png") %>" alt="">
    </a>
  </div>
  <div class="sidebar__menu">
    <ul>
      <li class="<%= active_sidebar(administrator_root_path, 'posts') %>">
        <a class="" href="<%= administrator_root_path %>">
          <img src="<%= asset_path("icon/product.svg") %>" alt="icon-product">
          <span>Posts</span>
        </a>
      </li>
      <li class="<%= active_sidebar(administrator_root_path, 'categories') %>">
        <a class="" href="<%= administrator_root_path %>">
          <img src="<%= asset_path("icon/category.svg") %>" alt="icon-category">
          <span>Categories</span>
        </a>
      </li>
      <li class="<%= active_sidebar(administrator_root_path, 'tags') %>">
        <a class="" href="<%= administrator_root_path %>">
          <img src="<%= asset_path("icon/tag.svg") %>" alt="icon-tag">
          <span>Tags</span>
        </a>
      </li>
      <li class="<%= active_sidebar(administrator_root_path, 'reports') %>">
        <a class="" href="<%= administrator_root_path %>">
          <img src="<%= asset_path("icon/detail.svg") %>" alt="icon-report">
          <span>Reports</span>
        </a>
      </li>
      <li class="">
        <a class="" href="">
          <img src="<%= asset_path("icon/comment.svg") %>" alt="icon-comment">
          <span>Comments</span>
        </a>
      </li>
      <li class="">
        <a class="" href="">
          <img src="<%= asset_path("icon/user.svg") %>" alt="icon-user">
          <span>Accounts</span>
        </a>
      </li>
      <li class="">
        <a class="" href="">
          <img src="<%= asset_path("icon/activity.svg") %>" alt="icon-activity">
          <span>Traffics</span>
        </a>
      </li>
      <li class="">
        <a class="" href="">
          <img src="<%= asset_path("icon/settings.svg") %>" alt="icon-settings">
          <span>Settings</span>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/administrator/base.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Admin | haotruong.dev</title>
    <%= favicon_link_tag asset_path("favicon.png"), rel: "icon", type: "image/x-icon" %>
    <%= stylesheet_link_tag :application_administrator, media: "all" %>
    <%= javascript_include_tag Ckeditor.cdn_url
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google" content="notranslate">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" rel="stylesheet" />
  </head>

  <body>
    <%= render "shared/flash" %>
    <div class="wrapper">
      <div class="section-left">
        <%= render "layouts/administrator/sidebar" %>
      </div>
      <div class="section-right">
        <%= render "layouts/administrator/header" %>
        <div class="main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/administrator/unauthenticate_layout.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login | haotruong.dev</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= favicon_link_tag asset_path("favicon.png"), rel: "icon", type: "image/x-icon" %>
    <%= stylesheet_link_tag :application_administrator, media: "all" %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
    <meta name="google" content="notranslate">
  </head>
  <body class="<%= yield :body_class %>">
    <%= render "shared/flash" %>
    <div class="unauthenticate__left">
      <div class="intro-banner">
        <div class="intro-banner__img">
          <img src="<%= asset_path("agency.png")%>">
        </div>
        <div class="intro-banner__text">
          <h1>#{Code} & Life</h1>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci provident culpa maiores ex veniam quaerat, veritatis tempore officia laborum qui distinctio suscipit ullam? Ipsa sapiente quas repellat nam facere. Doloribus.</p>
        </div>
      </div>
    </div>
    <div class="unauthenticate__right">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BioHaotruong</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% next if message.blank? %>
  <div id="toast">
    <div class="toast toast--<%= flash_class type.to_sym %>" style="animation: 0.3s ease 0s 1 normal none running slideInLeft, 1s linear 5s 1 normal forwards running fadeOut;">
      <div class="toast__icon">
        <img src="<%= asset_path("icon/#{flash_class type.to_sym}.svg") %>">
      </div>
      <div class="toast__body">
        <div class="toast__title"><%= flash_class type.to_sym %></div>
        <div class="toast__message">
          <%= message.html_safe %>
        </div>
      </div>
      <div class="toast__close">
        <img src="<%= asset_path("icon/close.svg") %>">
      </div>
    </div>
  </div>
<% end %>